### PR TITLE
Cindy

### PR DESCRIPTION
**Pull request by CindyRuth19**
Logo

### CODE REVIEW

**Review by Mayotopia04 — CHANGES_REQUESTED** [review]
Mam Cindy, have you put the pull_request_list.txt in the .gitignore file? because it should not be here in the repo, it should only be exclusive in your local device po. Please don't hesitate to ask me if u need more details

**Comment by CindyRuth19** [comment]
Hello po ma'am. Sinunod ko po yung instructions last time pero yan po ang result. 
    On Wednesday, July 3, 2024 at 10:44:09 PM GMT+8, Mayona Buck ***@***.***> wrote:  
 
 


@Mayotopia04 requested changes on this pull request.

Mam Cindy, have you put the pull_request_list.txt in the .gitignore file? because it should not be here in the repo, it should only be exclusive in your local device po. Please don't hesitate to ask me if u need more details

**Review by Mayotopia04 — CHANGES_REQUESTED** [review]
please fetch origin from main before sending pull request. will send msg in gc, thankx

**Review by Mayotopia04 — CHANGES_REQUESTED** [review]
please fetch origin from main before sending pull request. will send update in gc soon,  thanx,

**Pull request closed without merging**
